#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://123.57.135.88:3306/json-lu-blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: 123456

#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
